DROP DATABASE IF EXISTS pets;
CREATE DATABASE pets CHARACTER SET utf8mb4;
USE pets;

CREATE TABLE `user` (
	id_user INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	user_email VARCHAR(45) UNIQUE NOT NULL,
	user_password VARCHAR(45) NOT NULL
);

CREATE TABLE `pet` (
	id_pet INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	pet_name VARCHAR(40) NOT NULL,
	pet_breed VARCHAR(40) NOT NULL,
	pet_user INT UNSIGNED NULL,
	FOREIGN KEY (pet_user) REFERENCES `user`(id_user)
);

SELECT * FROM `user`;
SELECT * FROM `pet`;