DROP DATABASE IF EXISTS pets;
CREATE DATABASE pets CHARACTER SET utf8mb4;
USE pets;

CREATE TABLE users (
	id_user INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	email VARCHAR(40) UNIQUE NOT NULL,
	password VARCHAR(40) NOT NULL
);

CREATE TABLE pets (
	id_pet INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	name VARCHAR(40) NOT NULL,
	breed VARCHAR(40) NOT NULL,
	id_user INT UNSIGNED NULL,
	FOREIGN KEY (id_user) REFERENCES users(id_user)
);

SELECT * FROM USERS;
SELECT * FROM PETS;